language: python
python:
- '2.7'
branches:
  only:
  - master
install: pip install -r requirements.txt
script: pelican
notifications:
  slack:
    secure: bBkHOvZ/tlmwK4riRxNiIuDmSM3syJ9l9ClOEWKLITuPC+Yiv6lEs5F2IVaHKIM0AWF+fO3tTjG5N2oQSmnmOA9Wk6vU0WKiNrExbj02qszza2mLPjsGiEBHiLrNbX9x5jsFA73sXWOaj1E/dnqm5sMCJJUcYGIGd05nQ4O82NAD6E9GD5Liac17xOrGefCcxUtq5GHkpHDUC/SyFVFt1OcFf2/WukwRejfwfnL0BZT9q/dtm7yTfnrWE9zypFB1i2OR2uv8vADQB1AIXKjNykzmiZpvr8kMAMp7QATHl1f9AeCvDSLjnX3a29rXnt2w0pgiaDXiY8fz635sHleqQBXld37aDdtwpjyac4PRLxIHFuf7+aBXiTmmBsyspkV2eCPhYUhpE5XKLa37iFMX45nRL3+VFOZ5bD+kUuuPq/qiiVcRc1SX+cjoso8XV+O4FKSfNrTz0DNfEqjU5gBWqp2Ff4573K5RlBVq73P6MhvPTO+gr2NB3ArGAw/f6hGN4TmhPCBWBGRNyhMSZX2BI2tpC7b8dd4wW9vQxySpOVPv/mxFKP6T+AcS8iTQLLdhvLGAyT2RVj96J5XmaRQh5ykZa8k2qlIx/H5TsSIK6Z7/XGsY/23i1gzM2b+qBX3b1Cgzkin2Z+8xG5ZfdSj+tRkfsN2KZ5Nq0Cjee/dVVvM=
